/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_2nENcldG2",
        "userPoolWebClientId": "3j8h4ju8c69lp935hqqna1c9d8",
        "oauth": {
            "domain": "labs-auth.auth.us-east-1.amazoncognito.com",
            "scope": [
                "openid",
                "email",
                "profile"
            ],
            "redirectSignIn": "https://staging.d3pj4eqnytcy08.amplifyapp.com/",
            "redirectSignOut": "https://staging.d3pj4eqnytcy08.amplifyapp.com/",
            "responseType": "code"
        }
    }
};


export default awsmobile;
